sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t leslykqi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true leslykqi/react-test npm test

after_success:
  - docker build -t leslykqi/multi-client ./client
  - docker build -t leslykqi/multi-nginx ./nginx
  - docker build -t leslykqi/multi-server ./server
  - docker build -t leslykqi/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push themto docker hub
  - docker push leslykqi/multi-client
  - docker push leslykqi/multi-nginx
  - docker push leslykqi/multi-server
  - docker push leslykqi/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: multi-dockerenv: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-925348302516"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
