sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t leslykqi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true leslykqi/react-test npm test

after_success:
  - docker build -t leslykqi/multi-client ./client
  - docker build -t leslykqi/multi-nginx ./nginx
  - docker build -t leslykqi/multi-server ./server
  - docker build -t leslykqi/multi-worker ./worker
  # Log in to the docker CLI
  